import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "../components/Button";
import useUser from "../hooks/useUser";

export default function Home(props) {
  const [user, fetchUser] = useState(null);
  const { data, isLoading } = useUser();
  const artists = user ? user.artists : data?.artists;
  const genres = user ? user.genres : data?.genres;
  const arr = Array(20).fill(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Spotify Top Songs</h1>
        <Button fetchUser={fetchUser} />
        <section>
          {isLoading
            ? arr.map((_, index) => {
                return <div key={index}>nothing to see here</div>;
              })
            : artists.map((artist, index) => {
                console.log("hey it's", artist.artist);
                return <div key={index}>{artist.artist}</div>;
              })}
        </section>
      </main>
    </div>
  );
}
