import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "../components/Button";
import useUser from "../hooks/useUser";
import getNowPlayingItem from "../lib/spotify";

export default function Home(props) {
  const [user, fetchUser] = useState(null);
  const [loading, setLoading] = useState(true);
  const { data, isLoading } = useUser();
  const tracks = user ? user.tracks : data?.tracks;
  const arr = Array(20).fill(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Spotify Top Songs</h1>
        <Button fetchUser={fetchUser} />
        <section>here is your music</section>
      </main>
    </div>
  );
}
